"""add_uniqueness_to_photo

Revision ID: 2015f17d536d
Revises: 3073e2c41eb6
Create Date: 2023-03-24 06:28:30.977925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2015f17d536d'
down_revision = '3073e2c41eb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uniqueness', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['uniqueness'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('uniqueness')

    # ### end Alembic commands ###
