"""fix_photo_emotion_table_columns

Revision ID: 2736a57227cf
Revises: 3f1c043f5fe9
Create Date: 2022-11-18 08:19:49.346594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2736a57227cf'
down_revision = '3f1c043f5fe9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo_emotion', sa.Column('emotion_id', sa.Integer(), nullable=False))
    op.drop_constraint('photo_emotion_object_id_fkey', 'photo_emotion', type_='foreignkey')
    op.create_foreign_key(None, 'photo_emotion', 'emotions', ['emotion_id'], ['id'])
    op.drop_column('photo_emotion', 'object_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo_emotion', sa.Column('object_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'photo_emotion', type_='foreignkey')
    op.create_foreign_key('photo_emotion_object_id_fkey', 'photo_emotion', 'emotions', ['object_id'], ['id'])
    op.drop_column('photo_emotion', 'emotion_id')
    # ### end Alembic commands ###
