"""add_photo_associations

Revision ID: 5b6c86fbb296
Revises: 4051e0c243bb
Create Date: 2023-01-12 10:28:58.968715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b6c86fbb296'
down_revision = '4051e0c243bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('associations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=2048), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo_association',
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('association_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['association_id'], ['associations.id'], ),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ),
    sa.PrimaryKeyConstraint('photo_id', 'association_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo_association')
    op.drop_table('associations')
    # ### end Alembic commands ###
