"""add_photo_table

Revision ID: b0ef77c130de
Revises: 
Create Date: 2023-01-23 09:20:12.557889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0ef77c130de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('hash', sa.String(length=2048), nullable=True),
    sa.Column('photo_file_path_s3', sa.String(length=2048), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photos')
    # ### end Alembic commands ###
