image:
  registry: ghcr.io
  repository: tourmalinecore/tourmanique-api
  tag: ""
  pullPolicy: Always
  debug: false
  livenessProbe:
    enabled: false
  pullSecrets: []
  readinessProbe:
    enabled: false
  pullCredentials: {}
  
command:
  - "poetry"
args:
  - "run"
  - "flask"
  - "run"

podAnnotations:
  checksum/config: "{{ include (print $.Template.BasePath \"/extra-list.yaml\") . | sha256sum }}"

containerPorts:
  http: 5000

replicaCount: 1

resources:
  limits:
    cpu: 150m
    memory: 300Mi
  requests:
    cpu: 1m
    memory: 25Mi

livenessProbe:
  enabled: false

service:
  type: ClusterIP
  ports:
    http: 5000

ingress:
  enabled: true
  path: /api/
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt 
    nginx.ingress.kubernetes.io/rewrite-target: /api/$2
  ingressClassName: "nginx"
  tls: true

extraConfigMapEnvVars: {}

extraConfigMapEnvVarsEncoded: |
  {{- range $k, $v := .Values.extraConfigMapEnvVars }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
